services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: mail_system_db
    environment:
      POSTGRES_DB: db_mail_system
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mail_network

  # MailHog - SMTP Server para testing local
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mail_system_mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    networks:
      - mail_network

  # Aplicaci√≥n Java - Mail System
  mail_app:
    build: .
    container_name: mail_system_app
    depends_on:
      - postgres
      - mailhog
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: db_mail_system
      DB_USER: admin
      DB_PASSWORD: admin123
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
    networks:
      - mail_network

volumes:
  postgres_data:

networks:
  mail_network:
    driver: bridge
